// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CvContext))]
    partial class CvContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Content", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Key = "PROFILE_FULLNAME",
                            Value = "Edit the value in the administrator panel."
                        },
                        new
                        {
                            Key = "PROFILE_EMPLOYMENT",
                            Value = "Edit the value in the administrator panel."
                        },
                        new
                        {
                            Key = "ABOUT_TEXT",
                            Value = "Edit the value in the administrator panel."
                        },
                        new
                        {
                            Key = "ABOUT_BIRTHDATE",
                            Value = "25/10/2004"
                        },
                        new
                        {
                            Key = "ABOUT_EMAIL",
                            Value = "Edit the value in the administrator panel."
                        },
                        new
                        {
                            Key = "ABOUT_EMAIL_LINK",
                            Value = "mailto:maxmuster@example.com"
                        },
                        new
                        {
                            Key = "ABOUT_PHONE",
                            Value = "Edit the value in the administrator panel."
                        },
                        new
                        {
                            Key = "ABOUT_PHONE_LINK",
                            Value = "tel:0123456789"
                        },
                        new
                        {
                            Key = "ABOUT_GITHUB",
                            Value = "Edit the value in the administrator panel."
                        },
                        new
                        {
                            Key = "ABOUT_GITHUB_LINK",
                            Value = "https://github.com/maxmuster"
                        },
                        new
                        {
                            Key = "ABOUT_RESIDENCE",
                            Value = "Edit the value in the administrator panel."
                        });
                });

            modelBuilder.Entity("Domain.Models.Experience", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Text")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Company = "Example",
                            StartDate = new DateOnly(2020, 8, 1),
                            Text = "Edit the value in the administrator panel."
                        },
                        new
                        {
                            Id = 2L,
                            Company = "Elpmaxe",
                            EndDate = new DateOnly(2020, 7, 31),
                            StartDate = new DateOnly(2016, 1, 1),
                            Text = "Edit the value in the administrator panel."
                        });
                });

            modelBuilder.Entity("Domain.Models.Hobby", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Icon = "code",
                            Text = "Edit the value in the administrator panel."
                        },
                        new
                        {
                            Id = 2L,
                            Icon = "code",
                            Text = "Edit the value in the administrator panel."
                        });
                });

            modelBuilder.Entity("Domain.Models.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Skills", t =>
                        {
                            t.HasCheckConstraint("CK_Skill_Level", "'Level' >= 0 AND 'Level' <= 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Level = 70,
                            Name = "Edit the value in the administrator panel."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
